trigger:
  - main

variables:
  - group: my-variable-group

stages:
  - stage: Build
    jobs:
      - job: BuildJob
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.8'
              addToPath: true
          - script: |
              pip install -r requirements.txt
              pip install azure-functions
          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
          - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
            artifact: drop

  - stage: Deploy
    jobs:
      - job: DeployJob
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: AzureFunctionApp@1
            inputs:
              azureSubscription: 'my-azure-subscription'
              appType: 'functionApp'
              appName: 'my-function-app'
              package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'